---
- name: incluimos tareas cuando sea redhat
  include_tasks: 
    file: redhat.yml
  when: ansible_distribution == "RedHat"
  
- name: incluimos tareas cuando sea Ubuntu o Debian
  include_tasks: 
    file: ubuntu_debian.yml
  when: (ansible_distribution == "Ubuntu") or
        (ansible_distribution == "Debian")

- name: Bootstrap consul
  include_tasks:
    file: bootstrap.yml