---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  # - name: instance
  #   image: docker.io/pycontribs/centos:8
  #   pre_build_image: true
  - name: redhat
    image: docker.io/geerlingguy/docker-ubi8-ansible
    privileged: true
    required: true
    groups:
      - consul
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    networks:
      - name: "netconsul"
  - name: debian
    image: harbor.rancher.hsap.sacyl.es/library/docker-debian-systemd:latest
    # privileged: true
    required: true
    groups:
      - consul
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    networks:
      - name: "netconsul"
  - name: ubuntu
    image: harbor.rancher.hsap.sacyl.es/library/docker-ubuntu-systemd:latest
    # privileged: true
    required: true
    groups:
      - consul
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    networks:
      - name: "netconsul"
  - name: ubuntu-agente1
    image: harbor.rancher.hsap.sacyl.es/library/docker-ubuntu-systemd:latest
    # privileged: true
    required: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    networks:
      - name: "netconsul"
  - name: ubuntu-agente2
    image: harbor.rancher.hsap.sacyl.es/library/docker-ubuntu-systemd:latest
    # privileged: true
    required: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    networks:
      - name: "netconsul"
provisioner:
  name: ansible
verifier:
  name: ansible

